//auto-generated
package mikufan.cx.generate.appender;

import java.time.LocalDateTime;

/**
 * Commonly used util for adding things before class declaration
 */
public class CommonAppender {
  public static void addPackage(StringBuilder classStringBuilder, String yourPackage){
    classStringBuilder.append("package ").append(yourPackage).append(";\n");
  }
  public static void addEclispeCollAndLombokImport(StringBuilder classStringBuilder) {
    classStringBuilder.append("" +
        "import com.fasterxml.jackson.annotation.*;\n" +
        "import lombok.*;\n" +
        "import org.eclipse.collections.api.list.MutableList;\n");
  }

  public static void addBasicLombokAnnotationOnClass(StringBuilder classStringBuilder) {
    classStringBuilder.append("@Getter(onMethod_ = {@JsonIgnore}) @ToString\n");
  }

  public static void addLombokConstructorAnnotationOnClass(StringBuilder classStringBuilder) {
    classStringBuilder.append("@NoArgsConstructor\n").append("@AllArgsConstructor\n").append("@Builder\n");
  }

  public static void addComments(StringBuilder classStringBuilder) {
    classStringBuilder.append("// auto-generated by get-my-vocadb-java-model at ").append(LocalDateTime.now().toString()).append("\n");

  }
}
