// auto-generated by get-my-vocadb-java-model at 2020-12-18T02:33:31.825241
package dummy_package;

import lombok.*;
import lombok.experimental.FieldDefaults;
import lombok.extern.jackson.Jacksonized;

import java.util.List;

@Getter @ToString
@FieldDefaults(makeFinal = true, level = AccessLevel.PRIVATE)
@Builder(toBuilder = true) @Jacksonized
public final class Album {

   String additionalNames;
   String artistString;
   String coverPictureMime;
   String createDate;
   boolean deleted;
   String discType;
   int id;
   String name;
   double ratingAverage;
   int ratingCount;
   OptionalDateTime releaseDate;
   ReleaseEvent releaseEvent;
   String status;
   int version;

}
