// auto-generated by get-my-vocadb-java-model at 2020-06-24T21:05:23.248356
package dummy_package;

import com.fasterxml.jackson.annotation.*;
import lombok.*;
import org.eclipse.collections.api.list.MutableList;

@Getter(onMethod_ = {@JsonIgnore}) @ToString
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AlbumContract {

  @JsonProperty
  private String additionalNames;

  @JsonProperty
  private String artistString;

  @JsonProperty
  private String coverPictureMime;

  @JsonProperty
  private String createDate;

  @JsonProperty
  private boolean deleted;

  @JsonProperty
  private String discType;

  @JsonProperty
  private int id;

  @JsonProperty
  private String name;

  @JsonProperty
  private double ratingAverage;

  @JsonProperty
  private int ratingCount;

  @JsonProperty
  private OptionalDateTimeContract releaseDate;

  @JsonProperty
  private ReleaseEventForApiContract releaseEvent;

  @JsonProperty
  private String status;

  @JsonProperty
  private int version;

}
