// auto-generated by get-my-vocadb-java-model at 2020-08-20T16:50:42.005955800
package dummy_package;

import com.fasterxml.jackson.annotation.*;
import lombok.*;
import org.eclipse.collections.api.list.MutableList;

@Getter(onMethod_ = {@JsonIgnore}) @ToString
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ArtistContract {

  @JsonProperty
  private String additionalNames;

  @JsonProperty
  private String artistType;

  @JsonProperty
  private boolean deleted;

  @JsonProperty
  private int id;

  @JsonProperty
  private String name;

  @JsonProperty
  private String pictureMime;

  @JsonProperty
  private String releaseDate;

  @JsonProperty
  private String status;

  @JsonProperty
  private int version;

}
