// auto-generated by get-my-vocadb-java-model at 2020-12-17T22:35:44.8468854
package dummy_package;

import lombok.*;
import lombok.extern.jackson.Jacksonized;
import java.util.List;

@Getter @ToString
@Builder @Jacksonized
public class Artist {

  private String additionalNames;

  private String artistType;

  private boolean deleted;

  private int id;

  private String name;

  private String pictureMime;

  private String releaseDate;

  private String status;

  private int version;

}
