// auto-generated by get-my-vocadb-java-model at 2020-12-17T22:35:44.8259469
package dummy_package;

import lombok.*;
import lombok.extern.jackson.Jacksonized;
import java.util.List;

@Getter @ToString
@Builder @Jacksonized
public class ArtistForSong {

  private Artist artist;

  private String categories;

  private String effectiveRoles;

  private int id;

  private boolean isCustomName;

  private boolean isSupport;

  private String name;

  private String roles;

}
