// auto-generated by get-my-vocadb-java-model at 2020-12-18T01:55:55.9887452
package dummy_package;

import lombok.*;
import lombok.experimental.FieldDefaults;
import lombok.extern.jackson.Jacksonized;

import java.util.List;

@Getter @ToString
@FieldDefaults(makeFinal = true, level = AccessLevel.PRIVATE)
@Builder(toBuilder = true) @Jacksonized
public final class Artist {

   String additionalNames;

   String artistType;

   boolean deleted;

   int id;

   String name;

   String pictureMime;

   String releaseDate;

   String status;

   int version;

}
