// auto-generated by get-my-vocadb-java-model at 2020-12-18T02:33:31.8282343
package dummy_package;

import lombok.*;
import lombok.experimental.FieldDefaults;
import lombok.extern.jackson.Jacksonized;

import java.util.List;

@Getter @ToString
@FieldDefaults(makeFinal = true, level = AccessLevel.PRIVATE)
@Builder(toBuilder = true) @Jacksonized
public final class ArtistForSong {

   Artist artist;
   String categories;
   String effectiveRoles;
   int id;
   boolean isCustomName;
   boolean isSupport;
   String name;
   String roles;

}
