// auto-generated by get-my-vocadb-java-model at 2020-12-18T02:25:49.7822786
package dummy_package;

import lombok.*;
import lombok.experimental.FieldDefaults;
import lombok.extern.jackson.Jacksonized;

import java.util.List;

@Getter @ToString
@FieldDefaults(makeFinal = true, level = AccessLevel.PRIVATE)
@Builder(toBuilder = true) @Jacksonized
public final class EntryThumb {

   String mime;

   String urlOriginal;

   String urlSmallThumb;

   String urlThumb;

   String urlTinyThumb;

}
