// auto-generated by get-my-vocadb-java-model at 2020-12-17T22:35:44.8299294
package dummy_package;

import lombok.*;
import lombok.extern.jackson.Jacksonized;
import java.util.List;

@Getter @ToString
@Builder @Jacksonized
public class EntryThumb {

  private String mime;

  private String urlOriginal;

  private String urlSmallThumb;

  private String urlThumb;

  private String urlTinyThumb;

}
