// auto-generated by get-my-vocadb-java-model at 2020-08-20T16:50:41.991995500
package dummy_package;

import com.fasterxml.jackson.annotation.*;
import lombok.*;
import org.eclipse.collections.api.list.MutableList;

@Getter(onMethod_ = {@JsonIgnore}) @ToString
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class LocalizedStringContract {

  @JsonProperty
  private String language;

  @JsonProperty
  private String value;

}
