// auto-generated by get-my-vocadb-java-model at 2020-12-17T22:35:44.8279346
package dummy_package;

import lombok.*;
import lombok.extern.jackson.Jacksonized;
import java.util.List;

@Getter @ToString
@Builder @Jacksonized
public class LyricsForSong {

  private String cultureCode;

  private int id;

  private String source;

  private String translationType;

  private String url;

  private String value;

}
