// auto-generated by get-my-vocadb-java-model at 2020-08-20T16:50:42.026899900
package dummy_package;

import com.fasterxml.jackson.annotation.*;
import lombok.*;
import org.eclipse.collections.api.list.MutableList;

@Getter(onMethod_ = {@JsonIgnore}) @ToString
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class OptionalGeoPointContract {

  @JsonProperty
  private String formatted;

  @JsonProperty
  private boolean hasValue;

  @JsonProperty
  private double latitude;

  @JsonProperty
  private double longitude;

}
