// auto-generated by get-my-vocadb-java-model at 2020-12-17T22:35:44.8688261
package dummy_package;

import lombok.*;
import lombok.extern.jackson.Jacksonized;
import java.util.List;

@Getter @ToString
@Builder @Jacksonized
public class OptionalGeoPoint {

  private String formatted;

  private boolean hasValue;

  private double latitude;

  private double longitude;

}
