// auto-generated by get-my-vocadb-java-model at 2020-12-17T22:35:44.8448913
package dummy_package;

import lombok.*;
import lombok.extern.jackson.Jacksonized;
import java.util.List;

@Getter @ToString
@Builder @Jacksonized
public class OptionalDateTime {

  private int day;

  private String formatted;

  private boolean isEmpty;

  private int month;

  private int year;

}
