// auto-generated by get-my-vocadb-java-model at 2020-06-24T21:05:23.275284200
package dummy_package;

import com.fasterxml.jackson.annotation.*;
import lombok.*;
import org.eclipse.collections.api.list.MutableList;

@Getter(onMethod_ = {@JsonIgnore}) @ToString
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class OptionalDateTimeContract {

  @JsonProperty
  private int day;

  @JsonProperty
  private String formatted;

  @JsonProperty
  private boolean isEmpty;

  @JsonProperty
  private int month;

  @JsonProperty
  private int year;

}
