// auto-generated by get-my-vocadb-java-model at 2020-12-17T22:35:44.8349155
package dummy_package;

import lombok.*;
import lombok.extern.jackson.Jacksonized;
import java.util.List;

@Getter @ToString
@Builder @Jacksonized
public class PV {

  private String author;

  private int createdBy;

  private boolean disabled;

  private PVExtendedMetadata extendedMetadata;

  private int id;

  private int length;

  private String name;

  private String publishDate;

  private String pvId;

  private String service;

  private String pvType;

  private String thumbUrl;

  private String url;

}
