// auto-generated by get-my-vocadb-java-model at 2020-08-20T16:50:41.994983900
package dummy_package;

import com.fasterxml.jackson.annotation.*;
import lombok.*;
import org.eclipse.collections.api.list.MutableList;

@Getter(onMethod_ = {@JsonIgnore}) @ToString
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PVContract {

  @JsonProperty
  private String author;

  @JsonProperty
  private int createdBy;

  @JsonProperty
  private boolean disabled;

  @JsonProperty
  private PVExtendedMetadata extendedMetadata;

  @JsonProperty
  private int id;

  @JsonProperty
  private int length;

  @JsonProperty
  private String name;

  @JsonProperty
  private String publishDate;

  @JsonProperty
  private String pvId;

  @JsonProperty
  private String service;

  @JsonProperty
  private String pvType;

  @JsonProperty
  private String thumbUrl;

  @JsonProperty
  private String url;

}
