// auto-generated by get-my-vocadb-java-model at 2020-06-24T21:05:23.282264100
package dummy_package;

import com.fasterxml.jackson.annotation.*;
import lombok.*;
import org.eclipse.collections.api.list.MutableList;

@Getter(onMethod_ = {@JsonIgnore}) @ToString
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PVExtendedMetadata {

  @JsonProperty
  private String json;

}
