// auto-generated by get-my-vocadb-java-model at 2020-08-20T16:50:41.997976300
package dummy_package;

import com.fasterxml.jackson.annotation.*;
import lombok.*;
import org.eclipse.collections.api.list.MutableList;

@Getter(onMethod_ = {@JsonIgnore}) @ToString
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ReleaseEventForApiContract {

  @JsonProperty
  private String additionalNames;

  @JsonProperty
  private MutableList<ArtistForEventContract> artists;

  @JsonProperty
  private String category;

  @JsonProperty
  private String date;

  @JsonProperty
  private String description;

  @JsonProperty
  private String endDate;

  @JsonProperty
  private int id;

  @JsonProperty
  private EntryThumbForApiContract mainPicture;

  @JsonProperty
  private String name;

  @JsonProperty
  private MutableList<LocalizedStringContract> names;

  @JsonProperty
  private ReleaseEventSeriesContract series;

  @JsonProperty
  private int seriesId;

  @JsonProperty
  private int seriesNumber;

  @JsonProperty
  private String seriesSuffix;

  @JsonProperty
  private SongListBaseContract songList;

  @JsonProperty
  private String status;

  @JsonProperty
  private MutableList<TagUsageForApiContract> tags;

  @JsonProperty
  private String urlSlug;

  @JsonProperty
  private VenueForApiContract venue;

  @JsonProperty
  private String venueName;

  @JsonProperty
  private int version;

  @JsonProperty
  private MutableList<WebLinkForApiContract> webLinks;

}
