// auto-generated by get-my-vocadb-java-model at 2020-12-18T01:55:55.9997204
package dummy_package;

import lombok.*;
import lombok.experimental.FieldDefaults;
import lombok.extern.jackson.Jacksonized;

import java.util.List;

@Getter @ToString
@FieldDefaults(makeFinal = true, level = AccessLevel.PRIVATE)
@Builder(toBuilder = true) @Jacksonized
public final class ReleaseEventSeries {

   String additionalNames;

   String category;

   boolean deleted;

   String description;

   int id;

   String name;

   String pictureMime;

   String status;

   String urlSlug;

   int version;

   List<WebLink> webLinks;

}
