// auto-generated by get-my-vocadb-java-model at 2020-12-18T01:55:56.0106857
package dummy_package;

import lombok.*;
import lombok.experimental.FieldDefaults;
import lombok.extern.jackson.Jacksonized;

import java.util.List;

@Getter @ToString
@FieldDefaults(makeFinal = true, level = AccessLevel.PRIVATE)
@Builder(toBuilder = true) @Jacksonized
public final class ReleaseEvent {

   String additionalNames;

   String category;

   boolean customName;

   String date;

   boolean deleted;

   String description;

   String endDate;

   boolean hasVenueOrVenueName;

   int id;

   String inheritedCategory;

   String name;

   String pictureMime;

   ReleaseEventSeries series;

   SongListBase songList;

   String status;

   String urlSlug;

   Venue venue;

   String venueName;

   int version;

}
