// auto-generated by get-my-vocadb-java-model at 2020-12-17T22:35:44.8718176
package dummy_package;

import lombok.*;
import lombok.extern.jackson.Jacksonized;
import java.util.List;

@Getter @ToString
@Builder @Jacksonized
public class ReleaseEvent {

  private String additionalNames;

  private String category;

  private boolean customName;

  private String date;

  private boolean deleted;

  private String description;

  private String endDate;

  private boolean hasVenueOrVenueName;

  private int id;

  private String inheritedCategory;

  private String name;

  private String pictureMime;

  private ReleaseEventSeries series;

  private SongListBase songList;

  private String status;

  private String urlSlug;

  private Venue venue;

  private String venueName;

  private int version;

}
