// auto-generated by get-my-vocadb-java-model at 2020-12-19T03:10:29.8198705
package dummy_package;

import lombok.*;
import lombok.experimental.FieldDefaults;
import lombok.extern.jackson.Jacksonized;

import java.util.List;

@Getter @ToString
@FieldDefaults(makeFinal = true, level = AccessLevel.PRIVATE)
@Builder(toBuilder = true) @Jacksonized
public final class SongForApi {

   String additionalNames;
   List<Album> albums;
   List<ArtistForSong> artists;
   String artistString;
   String createDate;
   String defaultName;
   String defaultNameLanguage;
   boolean deleted;
   int favoritedTimes;
   int id;
   int lengthSeconds;
   List<LyricsForSong> lyrics;
   EntryThumbForApi mainPicture;
   int mergedTo;
   String name;
   List<LocalizedString> names;
   int originalVersionId;
   String publishDate;
   List<PV> pvs;
   String pvServices;
   int ratingScore;
   ReleaseEventForApi releaseEvent;
   String songType;
   String status;
   List<TagUsageForApi> tags;
   String thumbUrl;
   int version;
   List<WebLinkForApi> webLinks;

}
