// auto-generated by get-my-vocadb-java-model at 2020-08-20T16:50:42.015929600
package dummy_package;

import com.fasterxml.jackson.annotation.*;
import lombok.*;
import org.eclipse.collections.api.list.MutableList;

@Getter(onMethod_ = {@JsonIgnore}) @ToString
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class SongListBaseContract {

  @JsonProperty
  private String featuredCategory;

  @JsonProperty
  private int id;

  @JsonProperty
  private String name;

}
