// auto-generated by get-my-vocadb-java-model at 2020-12-17T22:35:44.8040006
package dummy_package;

import lombok.*;
import lombok.extern.jackson.Jacksonized;
import java.util.List;

@Getter @ToString
@Builder @Jacksonized
public class SongInList {

  private String notes;

  private int order;

  private Song song;

}
