// auto-generated by get-my-vocadb-java-model at 2020-12-18T01:55:55.9388777
package dummy_package;

import lombok.*;
import lombok.experimental.FieldDefaults;
import lombok.extern.jackson.Jacksonized;

import java.util.List;

@Getter @ToString
@FieldDefaults(makeFinal = true, level = AccessLevel.PRIVATE)
@Builder(toBuilder = true) @Jacksonized
public final class SongInList {

   String notes;

   int order;

   Song song;

}
