// auto-generated by get-my-vocadb-java-model at 2020-12-17T22:35:44.8648362
package dummy_package;

import lombok.*;
import lombok.extern.jackson.Jacksonized;
import java.util.List;

@Getter @ToString
@Builder @Jacksonized
public class TagBase {

  private String additionalNames;

  private String categoryName;

  private int id;

  private String name;

  private String urlSlug;

}
