// auto-generated by get-my-vocadb-java-model at 2020-08-20T16:50:41.999971
package dummy_package;

import com.fasterxml.jackson.annotation.*;
import lombok.*;
import org.eclipse.collections.api.list.MutableList;

@Getter(onMethod_ = {@JsonIgnore}) @ToString
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class TagUsageForApiContract {

  @JsonProperty
  private int count;

  @JsonProperty
  private TagBaseContract tag;

}
