// auto-generated by get-my-vocadb-java-model at 2020-06-24T20:55:05.193684700
package dummy_package;

import com.fasterxml.jackson.annotation.*;
import lombok.*;
import org.eclipse.collections.api.list.MutableList;

@Getter(onMethod_ = {@JsonIgnore}) @ToString
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class TagUsageForApiContract {

  @JsonProperty
  private int count;

  @JsonProperty
  private TagBaseContract tag;

}
