// auto-generated by get-my-vocadb-java-model at 2020-06-24T21:05:23.292237400
package dummy_package;

import com.fasterxml.jackson.annotation.*;
import lombok.*;
import org.eclipse.collections.api.list.MutableList;

@Getter(onMethod_ = {@JsonIgnore}) @ToString
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class VenueForApiContract {

  @JsonProperty
  private String additionalNames;

  @JsonProperty
  private String address;

  @JsonProperty
  private String addressCountryCode;

  @JsonProperty
  private OptionalGeoPointContract coordinates;

  @JsonProperty
  private String description;

  @JsonProperty
  private MutableList<ReleaseEventContract> events;

  @JsonProperty
  private int id;

  @JsonProperty
  private String name;

  @JsonProperty
  private MutableList<LocalizedStringContract> names;

  @JsonProperty
  private String status;

  @JsonProperty
  private int version;

  @JsonProperty
  private MutableList<WebLinkForApiContract> webLinks;

}
