// auto-generated by get-my-vocadb-java-model at 2020-06-24T20:55:05.223608400
package dummy_package;

import com.fasterxml.jackson.annotation.*;
import lombok.*;
import org.eclipse.collections.api.list.MutableList;

@Getter(onMethod_ = {@JsonIgnore}) @ToString
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class VenueContract {

  @JsonProperty
  private String additionalNames;

  @JsonProperty
  private String address;

  @JsonProperty
  private String addressCountryCode;

  @JsonProperty
  private OptionalGeoPointContract coordinates;

  @JsonProperty
  private boolean deleted;

  @JsonProperty
  private String description;

  @JsonProperty
  private int id;

  @JsonProperty
  private String name;

  @JsonProperty
  private String status;

  @JsonProperty
  private int version;

  @JsonProperty
  private MutableList<WebLinkContract> webLinks;

}
