// auto-generated by get-my-vocadb-java-model at 2020-12-17T22:35:44.866831
package dummy_package;

import lombok.*;
import lombok.extern.jackson.Jacksonized;
import java.util.List;

@Getter @ToString
@Builder @Jacksonized
public class WebLink {

  private String category;

  private String description;

  private String descriptionOrUrl;

  private boolean disabled;

  private int id;

  private String url;

}
